### PR TITLE
Add University Controller

### LINKED ISSUE #15: Add University Controller and Tests
# Acceptance Criteria:

- [x] There is <tt>UniversityController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [x] <tt>UniversityController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>UniversityQueryService</tt>, and returns the results.
- [x] The file  <tt>UniversityController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [x] The controller endpoint shows up on the Swagger UI page.
- [x] There is a <tt>UniversityControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [x] The tests in <tt>UniversityControllerTests</tt> provide 100% coverage of <tt>UniversityController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/w24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by sophiattran**
In this PR, we add an endpoint `/api/university/get` that can be used to get a list of universities that match a given name.

http://team01-sophiattran-dev.dokku-07.cs.ucsb.edu/

Closes #15

### CODE REVIEW

**Comment by theanimated01** [comment]
LGTM.
Dev deployment on dokku works as intended

**Comment by bwr02** [comment]
LGTM. Dokku is working

**Review by bwr02 — APPROVED** [review]

**Review by theanimated01 — APPROVED** [review]
LGTM. Dev deployment on dokku works

**Review by Shakcmpsc — APPROVED** [review]
LGTM

**Review by chloeqta — APPROVED** [review]
LGTM

**Pull request merged**
